# Generated by Django 6.0.4 on 2026-05-04 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('slack', 'Slack'), ('jira', 'Jira')], max_length=20)),
                ('contact_value', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-is_primary', 'contact_type'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('restructuring', 'Restructuring'), ('disbanded', 'Disbanded')], db_index=True, default='active', max_length=20)),
                ('email_distribution', models.EmailField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=100)),
                ('repo_type', models.CharField(choices=[('git', 'Git'), ('svn', 'SVN'), ('other', 'Other')], default='git', max_length=20)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('is_main', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('last_commit_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
                'ordering': ['-is_main', 'repo_name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('mission_purpose', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('restructuring', 'Restructuring'), ('disbanded', 'Disbanded')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['team_name'],
            },
        ),
        migrations.CreateModel(
            name='TeamActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('team_created', 'Team Created'), ('team_updated', 'Team Updated'), ('member_joined', 'Member Joined'), ('member_left', 'Member Left'), ('dep_added', 'Dependency Added'), ('dep_removed', 'Dependency Removed'), ('repo_added', 'Repository Added'), ('status_changed', 'Status Changed'), ('manager_assigned', 'Manager Assigned')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Team Activity',
                'verbose_name_plural': 'Team Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Null = currently active', null=True)),
                ('is_primary', models.BooleanField(default=True, help_text="Is this the user's primary team?")),
            ],
            options={
                'verbose_name': 'User Position',
                'verbose_name_plural': 'User Positions',
                'ordering': ['-start_date'],
            },
        ),
    ]
