# Generated by Django 6.0.4 on 2026-05-04 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_user',
            field=models.OneToOneField(blank=True, help_text='The department head. Deletion blocked while they hold this role.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='headed_department', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.ForeignKey(help_text='Department this team belongs to.', on_delete=django.db.models.deletion.RESTRICT, related_name='teams', to='teams.department'),
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Team manager. Null means team is unmanaged (flagged in reports).', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='managed_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repository',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='teams.team'),
        ),
        migrations.AddField(
            model_name='contact',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='teams.team'),
        ),
        migrations.AddField(
            model_name='teamactivity',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='teams.team'),
        ),
        migrations.AddField(
            model_name='teamactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userposition',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userposition',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team'),
        ),
        migrations.AddField(
            model_name='userposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('department', 'team_name')},
        ),
        migrations.AddIndex(
            model_name='teamactivity',
            index=models.Index(fields=['-created_at'], name='teams_teama_created_522e14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userposition',
            unique_together={('user', 'team', 'start_date')},
        ),
    ]
