# Generated by Django 6.0.4 on 2026-05-04 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('host', 'Host'), ('attendee', 'Attendee')], default='attendee', max_length=20)),
                ('attendance_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative')], default='pending', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Event Participant',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('deadline', 'Deadline'), ('review', 'Review')], default='meeting', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('platform', models.CharField(blank=True, default='', max_length=50)),
                ('meeting_link', models.URLField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(default='#4A90D9', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Schedule Event',
                'ordering': ['start_datetime'],
            },
        ),
    ]
