# Generated by Django 6.0.5 on 2026-05-05 21:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('downstream_team', models.ForeignKey(help_text='The team that depends on upstream (consumes the service)', on_delete=django.db.models.deletion.CASCADE, related_name='downstream_dependencies', to='teams.team')),
                ('upstream_team', models.ForeignKey(help_text='The team being depended ON (provides the service)', on_delete=django.db.models.deletion.CASCADE, related_name='upstream_dependencies', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team Dependency',
                'verbose_name_plural': 'Team Dependencies',
                'ordering': ['-criticality'],
                'unique_together': {('upstream_team', 'downstream_team')},
            },
        ),
    ]
